# 1934. Confirmation Rate
SELECT S.USER_ID,
    CASE WHEN C.TIME_STAMP IS NULL THEN 0.0
    ELSE ROUND(SUM(C.ACTION='CONFIRMED') / COUNT(*), 2)
    END AS CONFIRMATION_RATE
FROM SIGNUPS S LEFT JOIN CONFIRMATIONS C ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID
ORDER BY S.USER_ID