-- 그룹별 조건에 맞는 식당 목록 출력하기
WITH TBL1 AS
(SELECT MEMBER_ID, COUNT(MEMBER_ID) MAXMB FROM REST_REVIEW GROUP BY 1 ORDER BY 2 DESC LIMIT 1)

SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM
    MEMBER_PROFILE m
JOIN
    REST_REVIEW r
ON
    m.MEMBER_ID = r.MEMBER_ID
JOIN
    TBL1
ON
    m.MEMBER_ID = TBL1.MEMBER_ID
ORDER BY
    3 ASC, 2 ASC;