-- 입양 시각 구하기(2)

WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1 FROM HOUR_TABLE
    WHERE NUM < 23
)

SELECT HOUR_TABLE.NUM AS HOUR, IFNULL(ANIMAL_OUTS.COUNT, 0) AS COUNT
FROM HOUR_TABLE
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR ) AS ANIMAL_OUTS ON HOUR_TABLE.NUM = ANIMAL_OUTS.HOUR
ORDER BY HOUR_TABLE.NUM