-- 주문량이 많은 아이스크림들 조회하기

#1 UNION ALL
SELECT FLAVOR, SUM(TOTAL_ORDER) 
FROM (
    SELECT * FROM FIRST_HALF 
    UNION ALL
    SELECT * FROM JULY
    ) A
GROUP BY 1
ORDER BY SUM(TOTAL_ORDER) DESC LIMIT 3

#2 FROM 서브쿼리
SELECT f.FLAVOR
FROM FIRST_HALF f,
    (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL FROM JULY GROUP BY 1) j
WHERE f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL) DESC LIMIT 3