-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
WITH T1 AS (
SELECT DISTINCT rc.CAR_ID, rc.CAR_TYPE, ROUND((rc.DAILY_FEE * (1 - (dc.DISCOUNT_RATE / 100)) * 30), 0) FEE
FROM CAR_RENTAL_COMPANY_CAR rc
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dc
ON rc.CAR_TYPE = dc.CAR_TYPE
WHERE rc.CAR_TYPE IN ('세단', 'SUV') AND dc.DURATION_TYPE = '30일 이상'
), T2 AS (
SELECT T1.CAR_ID, T1.CAR_TYPE, T1.FEE
FROM T1
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY his
ON T1.CAR_ID = his.CAR_ID
WHERE his.CAR_ID NOT IN (SELECT CAR_ID from CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
GROUP BY T1.CAR_ID
)
SELECT CAR_ID, CAR_TYPE, FEE
FROM T2
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC